# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 18:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
